version: '3.7'

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    container_name: books-manager-api
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1:8000"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: postgres:12.0-alpine
    container_name: ${DBCONTAINERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DBUSERNAME}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: ${DBNAME}
    expose: 
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSERNAME} -d ${DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: