version: '3.7'

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    container_name: books-manager-api
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: ${DBCONTAINERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DBUSERNAME}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: ${DBNAME}
    expose: 
      - 5432

volumes:
  postgres_data: